version: '3.8'

services:
  pyytsync:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./pyytsync/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
