# Generated by Django 4.1.3 on 2022-12-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_video_id", models.CharField(max_length=50)),
                ("current_playtime", models.IntegerField()),
            ],
        ),
    ]
