# Generated by Django 4.2.8 on 2023-12-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50)),
                ('video_title', models.CharField(max_length=500, null=True)),
                ('order_num', models.IntegerField(null=True)),
                ('video_duration', models.CharField(default='00:00', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='VideoState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_video_id', models.CharField(max_length=50, null=True)),
                ('current_playtime', models.FloatField(null=True)),
                ('current_playlist_id', models.IntegerField(null=True)),
            ],
        ),
    ]
