# Generated by Django 4.1.3 on 2022-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videostate",
            name="current_playtime",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="videostate",
            name="current_video_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
