# Generated by Django 4.1.3 on 2022-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_alter_videostate_current_playtime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videostate",
            name="current_playtime",
            field=models.FloatField(null=True),
        ),
    ]
