# Generated by Django 4.1.4 on 2022-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_alter_videostate_current_playtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="videostate",
            name="current_playlist_id",
            field=models.IntegerField(null=True),
        ),
    ]
