# Generated by Django 4.1.4 on 2022-12-29 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0004_playlistvideo_videostate_current_playlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="videostate",
            name="last_next_playlist_video_time",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 29, 15, 57, 35, 107159)
            ),
        ),
    ]
