# Generated by Django 4.1.4 on 2022-12-29 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0007_alter_videostate_last_next_playlist_video_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videostate",
            name="last_next_playlist_video_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 29, 21, 13, 19, 301312, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
