# Generated by Django 4.1.4 on 2022-12-29 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0008_alter_videostate_last_next_playlist_video_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistvideo",
            name="video_title",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="videostate",
            name="last_next_playlist_video_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 12, 29, 22, 26, 5, 27651, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
