# Generated by Django 4.1.4 on 2023-01-04 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0009_playlistvideo_video_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlistvideo",
            name="order_num",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="videostate",
            name="last_next_playlist_video_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 4, 15, 9, 26, 871517, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
